# Generated by Django 5.1.1 on 2024-10-05 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 13, 48, 2, 889844, tzinfo=datetime.timezone.utc)),
        ),
    ]
